title: itsjunqing
name: Junqing Lim
description: A personal blog
github: itsjunqing
favicon: /assets/favicon/favicon.ico
email: itsjunqing@gmail.com
github_username: itsjunqing
linkedin_username: itsjunqing
avatar: assets/img/avatar/walking.gif

url: "itsjunqing.com"
baseurl: ""

permalink: /blog/:title

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
    - _sass/

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

blog:
  math: assets/img/blog/math
  exchange: assets/img/blog/exchange